### ISSUE TITLE
Does not load with VS 2017

### ISSUE THREAD

**Issue by alexgurman** [hybridview/ConfigurationSectionDesigner#1]
Getting an error after installing CSD.VS2017.vsix,  from AppData\Roaming\Microsoft\VisualStudio\15.0_e960bf7d\ActivityLog.xml:

 <description>LegacySitePackage failed for package [ConfigurationSectionDesignerPackage]Source: &apos;ConfigurationSectionDesigner.DslPackage&apos; Description: Could not load file or assembly &apos;ConfigurationSectionDesigner.Dsl, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null&apos; or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)&#x000D;&#x000A;System.IO.FileLoadException: Could not load file or assembly &apos;ConfigurationSectionDesigner.Dsl, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null&apos; or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)&#x000D;&#x000A;File name: &apos;ConfigurationSectionDesigner.Dsl, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null&apos;&#x000D;&#x000A;   at ConfigurationSectionDesigner.ConfigurationSectionDesignerPackageBase.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)&#x000D;&#x000A;&#x000D;&#x000A;</description>

**Comment by ItielBeeri** [comment]
I get this error too.

**Comment by hybridview** [comment]
Hmm... I think I have seen that before. I'll check it out.

**Comment by hybridview** [comment]
I turned on assembly signing for the DSL project and updated the release. Version is set to 2.0.3. Hopefully it works. I have a custom build of this tool installed on my dev machine here, so it is difficult to test the VSIX adequately.

**Comment by hybridview** [comment]
UPDATE: Found a possible versioning issue. Resolved and uploaded as 2.0.3.1.

**Comment by alexgurman** [comment]
Where do I download the installation from? http://csd.codeplex.com/releases doesn't seem to be updated.

**Comment by hybridview** [comment]
It is in the Releases part of GITHUB:

[https://github.com/hybridview/ConfigurationSectionDesigner/releases](https://github.com/hybridview/ConfigurationSectionDesigner/releases)

**Comment by DGuidi** [comment]
> It is in the Releases part of GITHUB

I suggest you to add a link to main page to this section: it's not immediate to found in main page

![screenshot_1](https://user-images.githubusercontent.com/216627/30063714-de60f226-924f-11e7-896d-0c73ab937e21.jpg)

![screenshot_2](https://user-images.githubusercontent.com/216627/30063715-ded4d4de-924f-11e7-9fce-9a4b18b7fdfc.jpg)

**Comment by hybridview** [comment]
I changed the message to use a link to the releases page as suggested.
