### ISSUE TITLE
Text Template Directives cause empty lines in xml files and break the notation

### ISSUE THREAD

**Issue by VassilTonev** [hybridview/ConfigurationSectionDesigner#10]
The directives in the text templates for xml files are not replaced "correctly" and the resulting xml file has its xml definition not at the top of the file, which breaks the file. The directives are replaced with blank lines. 
The problem is very well described [HERE](https://stackoverflow.com/questions/10478763/t4-templates-avoid-empty-lines-from-included-files). 
It must be said, that the bug itself is not in the CSD-Project (See the commect of Sebastian in the Stackoverflow discussion above), but nevertheless there is a solution/workaround, which is also described there(See the comment of B3ret).

In case the link is dead later:
Sebastian:

> The real reason is that every generated Template (it's cs code) has a \r\n in public virtual string TransformText() { this.Write(" \r\n");, so your answer is just working because the newline added by pressing return after each included template is omitted. – Sebastian May 21 '15 at 10:48

B3ret:

> To add to Tony's answer: You can avoid the very long lines by adding the linebreaks within the T4 brackets like so:
> 
> ```
> <#@ template debug="false" hostspecific="false" language="C#" #>
> <#@ output extension=".ttinclude" #>
> <#@ Import Namespace="System.Collections.Generic" #>
> <#@ Include file="Usings.tt" 
> #><#@ Include file="PropertyTypeEnum.tt" 
> #><#@ Include....
> #><#@ Include....
> #><#@ Include....
> #><#@ some other stuff 
> ```
> answered Nov 8 '13 at 14:02
> B3ret

What I did in the CSD-Project was to format the directives like so:
```
#><#@ output extension=".config" 
#><#@ assembly name="System.Configuration.dll" 
#><#@ assembly name="Microsoft.VisualStudio.Shell.Interop.8.0" 
#><#@ assembly name="Microsoft.VisualStudio.Shell.Interop.11.0" 
...
...
#><# Prepare(); #><?xml version="1.0"?>
```

This I did in the following files:
ConfigurationSectionDesignerSample.tt
ConfigurationSectionDesignerSchema.tt
source.extension.tt

**Comment by hybridview** [comment]
Thank you for the detailed analysis. I will try to get this in the next build.

**Comment by hybridview** [comment]
I looked into this and do not see the problem in my config files. I wonder if this is somehow environment related or due to some setting somewhere. I will keep this open and hope I can find a way to reproduce it.

**Comment by VassilTonev** [comment]
Hi,
it could be. I had the same, because nobody has submitted the "issue". Then I thought that the reason for that is that the problem is easy to correct (just manually delete the empty lines).

I'm using VS Community 2015 and installed the latest available version of the Modeling SDK for VS.

**Comment by hybridview** [comment]
I applied your fix to the VS2015 version for now to see how it goes. I have updated the VS2015 VSIX in  latest release on the releases page. Let me know if it does the trick for you.

**Comment by VassilTonev** [comment]
The newly uploaded version has fixed this problem too. :)
