### ISSUE TITLE
Generation errors in Visual Studio 2017 (15.2)

### ISSUE THREAD

**Issue by keymarkstuart** [hybridview/ConfigurationSectionDesigner#3]
I have a solution containing several projects, one has an existing configuration section designer object created originally in the VS2013 and for another project in this solution I need to add a new configuration section designer object.  In both projects, pressing save in the designer of the CSD file throws dozens of errors to the VS error list.

![image](https://user-images.githubusercontent.com/18489843/29324496-382a4446-81b2-11e7-8873-a4a4ead2e4bf.png)

I had this problem with the latest binary downloaded from this Github project so I also downloaded source and rebuilt the project myself and installed my own build of the extension.  Both show the same behavior.  What am I doing incorrectly here?

**Comment by Garwin4j** [comment]
I was getting this error, but when I install the latest github release : 2.0.3.1, it works and I have the same version of visual studio. 

If you are going to try to rebuild it, do you have **visual studio extension development** install?

**Comment by keymarkstuart** [comment]
Yes, I was able to rebuild it fine based on the current source in the Github repo.  The 2.0.3.alpha1 release has a post date of Jun 19 so it looks like the repo is more current, but I get the same behavior with both the release version and my own compiled version.

**Comment by keymarkstuart** [comment]
OK, I just patched this on my system.  I put the updates I used into a pull request if anyone else is seeing this issue.  #4
